version: '3.8'

services:
  # Feature Extraction API
  feature_extraction:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: low_level_feature_extraction
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - TESSERACT_PATH=/usr/bin/tesseract
      - OPENCV_IO_MAX_IMAGE_PIXELS=18446744073709551615
      - MAX_FILE_SIZE=16777216  # 16MB limit to match render.yaml
    ports:
      - "8000:8000"
