services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: image-processing-app
    ports:
      - "8000:8000"
    volumes:
      - ./performance_metrics:/app/performance_metrics
      - ./logs:/app/logs
    environment:
      - APP_ENV=development
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    restart: unless-stopped