version: '3.8'

services:
  # Feature Extraction API
  feature_extraction:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: low_level_feature_extraction
    volumes:
      - .:/app
    ports:
      - "8005:8005"
    restart: always
    depends_on:
      - ngrok
    networks:
      - feature_network
  ngrok:
    image: ngrok/ngrok:latest
    container_name: cont_ngrok
    command: http feature_extraction:8005 --url=comic-bug-ideally.ngrok-free.app
    environment:
      - NGROK_AUTHTOKEN=20SRiXyEOmPZtZUdYs6muKyZEX7_4WBxespUup36hs2WEHRxf
      - NGROK_REGION=ap # or 'us', 'eu', etc.
    restart: always
    networks:
      - feature_network
networks:
  feature_network:
    driver: bridge