services:
  - type: web
    name: feature-extraction-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MAX_CONTENT_LENGTH
        value: 16777216  # 16MB
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract
    healthCheckPath: /health
    plan: free  # Specify free tier
    scaling:
      minInstances: 1  # Minimum required instances
      maxInstances: 1  # Maximum one instance on free tier
